"""
Authentication module for Apple Music API.

Apple Music uses a two-token system:
  1. Developer Token  — a JWT you sign with your MusicKit private key (.p8).
                        Valid up to 6 months; auto-regenerated by this module.
  2. Music User Token — obtained once via MusicKit JS in a browser.
                        Stored in ~/.config/mcp-apple-music/config.json.
"""

import json
import time
from pathlib import Path
from typing import Optional

import jwt  # PyJWT

DEFAULT_CONFIG_PATH = Path.home() / ".config" / "mcp-apple-music" / "config.json"


class AppleMusicAuth:
    """Manages Developer Token generation and Music User Token retrieval."""

    def __init__(self, config_path: Path = DEFAULT_CONFIG_PATH):
        self.config_path = Path(config_path)
        self._config: Optional[dict] = None
        self._developer_token: Optional[str] = None
        self._token_expiry: float = 0

    # ------------------------------------------------------------------ #
    #  Config                                                              #
    # ------------------------------------------------------------------ #

    @property
    def config(self) -> dict:
        if self._config is None:
            self._config = self._load_config()
        return self._config

    def _load_config(self) -> dict:
        if not self.config_path.exists():
            raise FileNotFoundError(
                f"\n❌  Config not found: {self.config_path}\n"
                "    Run the setup wizard first:\n\n"
                "        python setup_auth.py\n"
            )
        with open(self.config_path) as f:
            return json.load(f)

    # ------------------------------------------------------------------ #
    #  Developer Token (JWT)                                               #
    # ------------------------------------------------------------------ #

    def get_developer_token(self) -> str:
        """Return a valid Developer Token, generating a new one if needed."""
        now = time.time()
        # Regenerate when expired or within 5 minutes of expiry
        if self._developer_token and now < self._token_expiry - 300:
            return self._developer_token

        key_path = Path(self.config["private_key_path"]).expanduser()
        if not key_path.exists():
            raise FileNotFoundError(f"MusicKit private key not found: {key_path}")

        with open(key_path) as f:
            private_key = f.read()

        expiry = int(now) + 15_777_000  # ≈ 6 months

        self._developer_token = jwt.encode(
            payload={
                "iss": self.config["team_id"],
                "iat": int(now),
                "exp": expiry,
            },
            key=private_key,
            algorithm="ES256",
            headers={"kid": self.config["key_id"]},
        )
        self._token_expiry = expiry
        return self._developer_token

    # ------------------------------------------------------------------ #
    #  Music User Token                                                    #
    # ------------------------------------------------------------------ #

    def get_music_user_token(self) -> str:
        """Return the Music User Token stored in config."""
        token = self.config.get("music_user_token", "")
        if not token:
            raise ValueError(
                "\n❌  Music User Token missing.\n"
                "    Run the setup wizard to authorise your Apple Music account:\n\n"
                "        python setup_auth.py\n"
            )
        return token

    # ------------------------------------------------------------------ #
    #  Helpers                                                             #
    # ------------------------------------------------------------------ #

    def get_storefront(self) -> str:
        """Return the two-letter storefront country code (e.g. 'it', 'us')."""
        return self.config.get("storefront", "us")

    def get_auth_headers(self) -> dict[str, str]:
        """Return the HTTP headers required by every Apple Music API request."""
        return {
            "Authorization": f"Bearer {self.get_developer_token()}",
            "Music-User-Token": self.get_music_user_token(),
        }

    def get_catalog_headers(self) -> dict[str, str]:
        """Headers for catalog-only requests (no user token required)."""
        return {"Authorization": f"Bearer {self.get_developer_token()}"}
